version: '3.8'
x-common-variables: &common-variables
  MYSQL_DATABASE: mysql_db
  MYSQL_USER: dbuser
  MYSQL_PASSWORD: qweqweasd
    
services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
  
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    ports:
      - 4001:4001
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - /app/example/node_modules
      - ./client:/app
    ports:
      - 3000:3000
  
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - "8089:8080"
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
  
  